from customWidgets.descriptiveWidget import descriptiveWidget
from customWidgets.datasetColumnLabel import datasetColumnLabel
from customWidgets.titleBar import CustomTitleBar
from customWidgets.userCanvas import userCanvas
from customWidgets.canvasCreationPage import canvasCreationPage
from customWidgets.viewDatasetTab import viewDatasetWidget
from customWidgets.chosenColumnLabel import chosenColumnLabel
from customWidgets.statTestCreatedWidget import statTestCreatedWidget